version: '3.1'
services:
    cassandra:
        image: stpic270/bd-secl-cassandra
        volumes:
            - cassandra_config:/config
        
        deploy:
            resources:
                limits:
                    cpus: "0.65"
                    memory: 1536M
                reservations:
                    cpus: "0.15"
                    memory: 512M
    
    model:
        image: stpic270/bd-thl-d:latest
        ports:
            - 77:70
        volumes:
            - cassandra_config:/app/test
    
volumes:
    cassandra_config: