pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('sikasi')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

    options {
            timestamps()
            skipDefaultCheckout(true)
        }

    stages {

        stage('Clone github repository') {
            steps {
                cleanWs()
                sh 'git clone -b main https://github.com/stpic270/Big_data_third_lab.git'
				}
			}

        stage('cd to repo') {
            steps {
                sh 'cd Big_data_third_lab && dir'
				}
			}

        stage('Login'){
            steps{
                //withCredentials([usernamePassword(credentialsId: 'sikasi', passwordVariable: 'DOCKER_REGISTRY_PWD', usernameVariable: 'DOCKER_REGISTRY_USER')]){
                //sh 'echo %DOCKER_REGISTRY_PWD% | docker login -u %DOCKER_REGISTRY_USER% --password-stdin'}
                // echo '%DOCKERHUB_CREDS_USR%'
                sh 'echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin'
                // sh 'docker login -u %DOCKERHUB_CREDS_USR% -p %DOCKERHUB_CREDS_PSW%'
                }
            }
        
        stage('Run docker compose') {
            steps {
                sh  '''
                cd Big_data_third_lab && docker compose build
                docker compose up -d --no-start
                    '''
                }
            }
            
        stage('Start containers'){
            steps{
                dir("Big_data_third_lab"){

                    sh 'docker start big_data_third_lab-model-1'
                    
                    echo "Waiting 60 seconds for entrypoint script"
                    sleep 60
                    
                    sh  '''
                        docker start big_data_third_lab-cassandra-1
                        docker exec big_data_third_lab-cassandra-1 bash -c "echo '\n' >> config/cassandra_ip.txt && ip -4 -o address >> config/cassandra_ip.txt"
                        docker exec -i big_data_third_lab-model-1 bash -c "scripts/cassandra.sh"
                        docker compose stop
                        '''
                    }
                }
            }
            
        stage('Checkout coverage report') {
            steps {
                sh  '''
                    docker logs --tail 30 -f big_data_third_lab-model-1
                    '''
            }
        }

        stage('Push'){
            steps{
                sh 'docker push stpic270/bd-thl-d:latest'
                sh 'docker push stpic270/bd-secl-cassandra:latest'
            }
        }
        
        stage('Post always'){
            steps{
                 sh 'docker logout'
            }
        }
    }
}